name: openapi-issue
version: 0.1.0.0
github: "githubuser/openapi-issue"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/openapi-issue#readme>

dependencies:
  - base >= 4.7 && < 5
  - text == 1.2.4.1
  - servant == 0.18.2
  - servant-server == 0.18.2
  - servant-client == 0.18.2
  - openapi3 == 3.0.1.0
  - servant-openapi3 == 2.0.1.1
  - uuid == 1.3.14
library:
  source-dirs: src

executables:
  openapi-issue-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - openapi-issue

tests:
  openapi-issue-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - openapi-issue
